### ISSUE TITLE
not sure if the code is using 4 nodes each having 4 GPUs?

### ISSUE THREAD

**Issue by monajalal** [Microsoft/MLOps_Hub#75]
so I requested for 4 nodes and 4 GPUs each, and also made that cluster myself in compute. When my cluster is being used, it shows there is only 1 active run but 4 busy node. I am using DistributedDataParallel in PyTorch for a computer vision-based deep learning code.

Could you explain why I don't have 4 active runs and instead I have 4 busy node? What is wrong and how it could be fixed?

```
jobs:
  train:
    type: command
    component: file:train.yaml
    # compute: azureml:gpu-cluster
    compute: azureml:mona-gpu-cluster
    # compute: azureml:single-node-cluster
    resources:
      instance_count: 4    # number of nodes
      # instance_count: 1  # set to 1 for testing purposes
    distribution:
      type: pytorch
      process_count_per_instance: 4 # number of gpus
      # process_count_per_instance: 1 # set to 1 for testing purposes
```
this is from pipeline.yaml that I am using based off mlops-templates

![Screenshot from 2023-04-06 17-12-16](https://user-images.githubusercontent.com/1892917/230495419-4e2da147-54b7-4763-b135-f7750da655ef.png)
